name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm
      
      # Next.js build
      - name: Install dependencies
        run: npm ci
        
      - name: Build Next.js
        run: npm run build
        
      # Docusaurus build
      - name: Install doc dependencies
        run: cd doc && npm ci
        
      - name: Build doc
        run: cd doc && npm run build
        
      # Combine builds
      - name: Combine builds
        run: |
          mkdir -p combined-build
          cp -r out/* combined-build/
          mkdir -p combined-build/doc
          cp -r doc/build/* combined-build/doc/
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: combined-build

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
