name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Update to v4
        
      - name: Setup Node
        uses: actions/setup-node@v4  # Update to v4
        with:
          node-version: "18.1"
          cache: npm
      
      - name: Install dependencies
        run: npm ci
        
      - name: Build Next.js
        run: npm run build
        
      - name: Install doc dependencies
        run: cd doc && npm ci
        
      - name: Build doc
        run: cd doc && npm run build
        
      - name: Configure Pages
        uses: actions/configure-pages@v3
      
      - name: Combine builds
        run: |
          mkdir -p _site
          cp -r out/* _site/
          mkdir -p _site/doc
          cp -r doc/build/* _site/doc/
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2  # Update to v2
