name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch name

permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build for GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm
      
      # Debug repository structure
      - name: List repository structure
        run: ls -la
      
      # Build Next.js app from root directory
      - name: Install Next.js dependencies
        run: npm ci
      
      - name: Build Next.js app
        run: |
          npm run build
          # Run export if needed
          if [ ! -d "out" ]; then
            npm run export || echo "Export command might not be needed"
          fi
      
      # Build Docusaurus from doc directory
      - name: Install Docusaurus dependencies
        run: cd doc && npm ci
      
      - name: Build Docusaurus
        run: cd doc && npm run build

      # Combine the builds
      - name: Prepare combined build
        run: |
          mkdir -p combined-build
          
          # Check for Next.js output
          if [ -d "out" ]; then
            echo "Copying Next.js output"
            cp -r out/* combined-build/
          else 
            echo "No 'out' directory found. Checking alternative locations..."
            if [ -d ".next/out" ]; then
              cp -r .next/out/* combined-build/
            elif [ -d ".next" ]; then
              echo "Using .next directory content"
              cp -r .next/* combined-build/
            else
              echo "ERROR: No Next.js output found!"
              exit 1
            fi
          fi
          
          # Check for Docusaurus output
          mkdir -p combined-build/doc
          if [ -d "doc/build" ]; then
            echo "Copying Docusaurus output"
            cp -r doc/build/* combined-build/doc/
          else
            echo "ERROR: No doc/build directory found!"
            ls -la doc
            exit 1
          fi
          
          echo "Combined build directory contents:"
          ls -la combined-build

      # Use the correct upload artifact action for GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: combined-build

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2